FROM jupyter/pyspark-notebook:latest

# Switch to root to install system / python deps
USER root

# (Optional but recommended) Upgrade pip
RUN pip install --no-cache-dir --upgrade pip

# Install Python dependencies
RUN pip install --no-cache-dir \
    requests \
    kafka-python \
    python-dotenv \
    hdfs

# Switch back to jovyan (required for Jupyter)
USER jovyan
CMD ["start-notebook.sh"]
